---
title: "Welcome to Vices - A Users Guide"
description: |
  This is the syllabus for the course. It includes links to the papers that we will read.
author:
  - name: Brian Weatherson
    url: http://brian.weatherson.org
    affiliation: University of Michigan
    affiliation_url: https://lsa.umich.edu/philosophy
date: 08-24-2021
output:
  distill::distill_article:
    self_contained: false
---

<div id="course-description" class="section level1">
<h1>Course Description</h1>
<p>This course has two parts. The first part concerns philosophical work on the nature of thick concepts, and in particular whether the existence of these thick concepts poses a threat to the idea that there is a fact/value distinction. The second part of the course concerns particular thick concepts, with a special focus on those that are relevant to both ethics and epistemology.
</div>
<div id="canvas" class="section level1">
<h1>Canvas</h1>
<p>There is a Canvas site for this course, which can be accessed from <a href="https://canvas.umich.edu" class="uri">https://canvas.umich.edu</a>. Course documents (syllabus, lecture notes, assignments) will be available from this site. Please make sure that you can access this site. Consult the site regularly for announcements, including changes to the course schedule. And there are many tools on the site to communicate with each other, and with me.
</div>
<div id="required-materials" class="section level1">
<h1>Required Materials</h1>
<p>There is one required book for the course.
<ul>
<li><em>The Lewd, the Rude and the Nasty: A Study of Thick Concepts in Ethics</em> by Pekka Väyrynen. (This will be referred to as LRN in what follows.)</li>
</ul>
<p>It’s also highly recommended that you get
<ul>
<li><em>Ethics and the Limits of Philosophy</em> by Bernard Williams. (This will be referred to as ELP in what follows.)</li>
<li><em>Thick Evaluations</em> by Simon Kirchin - this is freely available at <a href="https://global.oup.com/academic/product/thick-evaluation-9780198803430" class="uri">https://global.oup.com/academic/product/thick-evaluation-9780198803430</a>. (Look for ‘open access’ in top right.)</li>
</ul>
<p>There are some assigned readings from it, but I’ll try to make them available to anyone who doesn’t have a copy. But if you’re working in ethics, it’s probably one of the books you should have on your shelf anyway.
<p>The other readings will all be available through the university library, and will be linked on Canvas.
</div>
<div id="course-requirements" class="section level1">
<h1>Course Requirements</h1>
<ol style="list-style-type: decimal">
<li>Participate in the classes each week, having done the reading.</li>
<li>Write four ‘weeklies’ at some point during the term. A weekly should be a 2-3 page paper making one good point (either a criticism, or an application to some other debate) about the reading for that week. These do not need to include summaries of the text; assume the reader knows what you’re talking about.</li>
<li>In every week that you don’t write a weekly, leave (at least) one question about (at least) one of the papers from the reading on the Canvas discussion boards.</li>
<li>When possible, answer some of the questions on the boards, and contribute to discussions there.</li>
<li>Write one short paper (about 10-12 pages, or about 3000 words) on one of the topics we discuss in the course.</li>
</ol>
<p>The weeklies, and the short paper, may be co-authored. (I don’t know what it would be to co-author a question, though you should give credit to someone if the question came out of discussions with them.)
</div>
<div id="summary-of-grading-system" class="section level1">
<h1>Summary of Grading System</h1>
<ol style="list-style-type: decimal">
<li>Participation in discussion boards and online classes - 20%</li>
<li>Weeklies - 4 by 10% = 40%</li>
<li>Short paper - 40%</li>
</ol>
</div>
<div id="plagiarism" class="section level1">
<h1>Plagiarism</h1>
<p>Although team-work, and even co-authorship, is encouraged, plagiarism is strictly prohibited. You are responsible for making sure that none of your work is plagiarized. Be sure to cite work that you use, both direct quotations and paraphrased ideas. Any citation method that is tolerably clear is permitted, but if you’d like a good description of a citation scheme that works well in philosophy, look at <a href="http://bit.ly/VDhRJ4" class="uri">http://bit.ly/VDhRJ4</a>.
<p>You are encouraged to discuss the course material, including assignments, with your classmates, but all written work that you hand in under your own name must be your own. If work is handed is as the work of two people, you are affirming that each person did a fair share of the work. (Note that when you’re submitting work on Canvas, you have to each submit the paper, even if it is co-authored. That way Canvas knows that everyone has turned in work.)
<p>You should also be familiar with the academic integrity policies of the College of Literature, Science &amp; the Arts at the University of Michigan, which are available here: <a href="http://www.lsa.umich.edu/academicintegrity/" class="uri">http://www.lsa.umich.edu/academicintegrity/</a>. Violations of these policies will be reported to the Office of the Assistant Dean for Student Academic Affairs, and sanctioned with a course grade of F.
</div>
<div id="disability" class="section level1">
<h1>Disability</h1>
<p>The University of Michigan abides by the Americans with Disabilities Act of 1990, Section 504 of the Rehabilitation Act of 1973, and other applicable federal and state laws that prohibit discrimination on the basis of disability, which mandate that reasonable accommodations be provided for qualified students with disabilities.
<p>If you have a disability, and may require some type of instructional and/or examination accommodation, please contact me early in the semester. If you have not already done so, you will also need to register with the Office of Services for Students with Disabilities. The office is located at G664 Haven Hall.
<p>For more information on disability services at the University of Michigan, go to <a href="http://ssd.umich.edu" class="uri">http://ssd.umich.edu</a>.
<div style="page-break-after: always;"></div>
</div>
<div id="class-schedule" class="section level1">
<h1>Class Schedule</h1>
<p>Students must read the following before Monday’s class session. Important: class readings are subject to change, contingent on circumstances and the progress we make as a class. Students are encouraged to attend lectures and check the course website for updates. The links to readings will often be to things behind paywalls, but they are (I believe) all things you have access to through the UM library. You might have to be logged in to UM to get them though.
<p>For each week, we’ll go through the readings in the order they are here. That doesn’t mean they are in order of importance; a couple of times there is a reading I want to focus on, but we need to briefly discuss something else to set it up. So each week I’ve starred the one that is really most crucial, though it might not be stuff we start with. Also, we’ll open each week with an open floor for any questions/comments/etc about anything on the list. After that I’ll work through things in the order they appear here, with the intent of going in the order shown.
<p>It might not be obvious, but many of the paper titles below contain links to places the paper is accessible. (In some cases, that includes places where I have made them accessible, mostly legally.)
<p>Note that because we really aren’t expecting everyone to do the recommended reading, if you want to make a point about something in the recommended reading, you might need to provide a bit of background to any comment. (This isn’t important for the discussion boards, but it is important in class.) But you should assume everyone is familiar with the required readings, especially the starred ones.
<div id="week-01-0830-the-fact-value-distinction" class="section level2">
<h3>Week 01, 08/30: The Fact-Value Distinction</h3>
<ul>
<li>LRN chapter 1, especially subsection 1.4.2.</li>
<li>*G. E. Moore, Chapter 1 of <a href="https://brian.weatherson.org/gutenberg-files/principia_ethica/">Principia Ethica</a>, especially §§10-13.</li>
</ul>
<p><em>Highly Recommended</em>
<ul>
<li>John Maynard Keynes, <a href="http://brian.weatherson.org/meb.html">My Early Beliefs</a>.</li>
</ul>
<p><em>Recommended</em>
<ul>
<li>William Frankena, <a href="https://www.jstor.org/stable/2250706?seq=1#metadata_info_tab_contents">The Naturalistic Fallacy</a>.</li>
<li>Pekka Väyrynen, <a href="https://plato.stanford.edu/entries/thick-ethical-concepts/">Thick Ethical Concepts</a> in the Stanford Encyclopaedia, especially §2.1.</li>
<li>Simon Kirchin, <em>Thick Evaluation</em>, chapter 1, especially pages 11-15.</li>
</ul>
</div>
<div id="week-02-0906-labor-day---no-class" class="section level2">
<h3>Week 02, 09/06: Labor Day - No Class</h3>
</div>
<div id="week-03-0913-problems-for-the-distinction" class="section level2">
<h3>Week 03, 09/13: Problems for the Distinction</h3>
<ul>
<li>Arthur Prior, <a href="https://www.tandfonline.com/doi/abs/10.1080/00048406085200221">The Automomy of Ethics</a>.</li>
<li>*Philippa Foot, <a href="https://www.jstor.org/stable/2251201">Moral Arguments</a>.</li>
<li>ELP, Chapter 7.</li>
</ul>
<p><em>Recommended</em>
<ul>
<li>Iris Murdoch, <a href="https://www.jstor.org/stable/4106662?seq=19#metadata_info_tab_contents">Vision and Choice in Morality</a>.</li>
<li>Greg Restall and Gillian Russell, <a href="https://consequently.org/papers/barriers.pdf">Barriers to Implication</a>.</li>
</ul>
</div>
<div id="week-04-0920-williams-on-thick-concepts" class="section level2">
<h3>Week 04, 09/20: Williams on Thick Concepts</h3>
<ul>
<li>ELP, Chapters 8-10 (especially 8).</li>
</ul>
<p><em>Recommended</em>
<ul>
<li>Simon Kirchin, <em>Thick Evaluation</em>, chapter 8.</li>
<li>LRN, §§10.2-3.</li>
</ul>
</div>
<div id="week-05-0927-shapelessness" class="section level2">
<h3>Week 05, 09/27: Shapelessness</h3>
<ul>
<li>John McDowell, <a href="http://brian.weatherson.org/640-F21/McDowell.pdf">Non-Cognitivism and Rule Following</a>.</li>
</ul>
<p><em>Recommended</em>
<ul>
<li>Simon Blackburn, <a href="http://brian.weatherson.org/640-F21/Blackburn.pdf">Reply: Rule Following and Moral Realism</a>.</li>
<li>Debbie Roberts, <a href="https://www.jstor.org/stable/10.1086/658898">Shapelessness and the Thick</a>.</li>
<li>Simon Kirchin, <em>Thick Evaluation</em>, chapter 5.</li>
<li>LRN, Chapter 8.</li>
</ul>
</div>
<div id="week-06-1004-semantic-views" class="section level2">
<h3>Week 06, 10/04: Semantic Views</h3>
<ul>
<li>*Daniel Elstein and Thomas Hurka, <a href="https://www.jstor.org/stable/27822063">From Thick to Thin: Two Moral Reduction Plans</a>.</li>
<li>LRN, Chapter 3.</li>
</ul>
<p><em>Recommended</em>
<ul>
<li>LRN, Chapter 4.</li>
<li>Brent Kyle, <a href="http://hdl.handle.net/2027/spo.3521354.0013.001">How are Thick Terms Evaluative?</a>.</li>
<li>Michael Smith, <a href="http://www.princeton.edu/~msmith/mypapers/Thick%20and%20Thin.pdf">On the Nature and Significance of the Distinction Between Thick and Thin Ethical Concepts</a>.</li>
<li>Simon Kirchin, <em>Thick Evaluation</em>, §§2.4-2.6.</li>
</ul>
<div style="page-break-after: always;"></div>
</div>
<div id="week-07-1011-pragmatic-views" class="section level2">
<h3>Week 07, 10/11: Pragmatic Views</h3>
<ul>
<li>LRN, Chapter 5.</li>
</ul>
<p><em>Recommended</em>
<ul>
<li>Simon Kirchin, <em>Thick Evaluation</em>, Chapter 7.</li>
<li>Debbie Roberts, <a href="https://www.journals.uchicago.edu/doi/10.1086/679534">Review of The Lewd, the Rude and the Nasty: A Study of Thick concepts in Ethics by Pekka Vayrynen</a>.</li>
<li>Bianca Cepollaro and Isidora Stojanovic, <a href="https://brill.com/view/journals/gps/93/3/article-p458_7.xml">Hybrid Evaluatives: In Defense of a Presuppositional Account</a>.</li>
</ul>
</div>
<div id="week-08-1018-fall-study-break" class="section level2">
<h3>Week 08, 10/18: Fall Study Break</h3>
<p>This falls at a nice time, since it breaks the course in two between the general study of thick concepts, and looking at specific important thick concepts.
</div>
<div id="week-09-1025-modesty-in-ethics" class="section level2">
<h3>Week 09, 10/25: Modesty in Ethics</h3>
<ul>
<li>*Julia Driver, <a href="https://www.jstor.org/stable/2027146">The Virtues of Ignorance</a>.</li>
<li>G. F. Schueler, <a href="https://www.jstor.org/stable/2382326">Why Modesty Is a Virtue</a>.</li>
</ul>
<p><em>Recommended</em>
<ul>
<li>ELP, Chapter 1.</li>
<li>Julia Driver, <a href="https://www.jstor.org/stable/10.1086/233947">Modesty and Ignorance</a>.</li>
<li>G. F. Schueler, <a href="https://doi.org/10.1086/233948">Why Is Modesty a Virtue?</a>.</li>
<li>Nicolas Bommarito, <a href="https://plato.stanford.edu/entries/modesty-humility/">Modesty and Humility</a>.</li>
</ul>
</div>
<div id="week-10-1101-modesty-in-epistemology" class="section level2">
<h3>Week 10, 11/01: Modesty in Epistemology</h3>
<ul>
<li>Ian Church, <a href="http://logos-and-episteme.acadiasi.ro/the-doxastic-account-of-intellectual-humility-pages-413-433/">The Doxastic Account of Intellectual Humility</a>.</li>
<li>Alessandra Tanesini, <a href="https://onlinelibrary.wiley.com/doi/abs/10.1111/phpr.12326">Intellectual Humility as Attitude</a>.</li>
</ul>
<p><em>Recommended</em>
<ul>
<li>Duncan Pritchard, <a href="https://link-springer-com.proxy.lib.umich.edu/article/10.1007%2Fs11229-018-02024-5">Intellectual humility and the epistemology of disagreement</a>.</li>
<li>Michael Lynch, <a href="https://www.cambridge.org/core/journals/episteme/article/abs/arrogance-truth-and-public-discourse/EB7618E77489F730D5020C3B88119285">Arrogance, Truth and Public Discourse</a>.</li>
<li>Alexandra Plakias, <a href="https://link.springer.com/article/10.1007/s10677-020-10093-0">Some Probably-Not-Very-Good Thoughts on Underconfidence</a>.</li>
</ul>
<p>NB: There is a huge and growing literature on this, and I’d be particularly happy to take recommendations for more readings on this particular question.
<div style="page-break-after: always;"></div>
</div>
<div id="week-11-1108-hypocrisy" class="section level2">
<h3>Week 11, 11/08: Hypocrisy</h3>
<ul>
<li>*Danielle Dover, <a href="https://doi.org/10.1215/00318108-7697850">The Walk and the Talk</a>.</li>
<li>Kyle G. Fritz &amp; Daniel Miller, <a href="https://quod.lib.umich.edu/e/ergo/12405314.0006.019/--unique-badness-of-hypocritical-blame?rgn=main;view=fulltext">The Unique Badness of Hypocritical Blame</a>.</li>
</ul>
<p><em>Recommended</em>
<ul>
<li>Hannah Tierney, <a href="https://doi.org/10.1093/analys/anaa074">Hypercrisy and standing to self-blame</a>.</li>
<li>Kasper Lippert-Rasmussen, <a href="https://doi.org/10.1093/analys/anaa009">Why the moral equality account of the hypocrite’s lack of standing to blame fails</a>.</li>
</ul>
</div>
<div id="week-12-1115-open" class="section level2">
<h3>Week 12, 11/15: Open</h3>
</div>
<div id="week-13-1122-open" class="section level2">
<h3>Week 13, 11/22: Open</h3>
</div>
<div id="week-14-1129-open" class="section level2">
<h3>Week 14, 11/29: Open</h3>
<p>We’ll discuss which virtues/vices/thick concepts we want to focus on in these weeks in weeks 1 and 2, and I’ll update this part of the syllabus with more readings.
</div>
<div id="week-15-1206-review" class="section level2">
<h3>Week 15, 12/06: Review</h3>
<p>We’ll go over some themes from the course, and if anyone wants to do a presentation on their essay topic we can do some then. This is writing/grading time for most students, so we certainly won’t do new material. But I think there will be value in having a chance to review what we’ve covered, and for anyone to discuss things that came up when they were doing more reading for the short papers.
</div>
</div>








