---
title: "Week Five: Semantic Arguments"
description: |
  There are three aims for the week. The first is to go over an argument of McDowell's that I didn't get to last week, arguing that non-cognitivists have trouble explaining the non-arbitrariness of our use of thick terms. The second is to set out Elstein and Hurka's reductive semantic theory of thick terms. And the third is to introduce Väyrynen's objections to semantic accounts.
author:
  - name: Brian Weatherson
    url: http://brian.weatherson.org
date: 10-04-2021
bibliography: ../../../articles/Rbib.bib
preview: hurka.jpg
categories:
  - shapelessness
  - semantic model
  - rejected terms
output:
  distill::distill_article:
    self_contained: false
    toc: true
    toc_depth: 3
    number_sections: true
---

### Separation Arguments


There are a few arguments circulating around about how the difficulty of separating out the descriptive part of thick concepts tells us ... _something_ ... about the nature of value. Some of these look like really terrible arguments, but I think there's a pretty good one in section 5 of McDowell's 1981 paper [@McDowell1981].

But let's start with an argument from section 2 of that paper. This argument seems to be more widely discussed, and also a very bad argument. The former is a reason to discuss it; the latter is a reason to be a bit quick about it. Here's how I'd reconstruct the argument.

1. If non-cognitivism is true, then some reductive analysis of thick concepts into maximally thin concepts plus descriptive stuff is possible.
2. If such a reductive analysis is possible, then there is a descriptive concept that is necessarily extensionally equivalent to the thick concept.
3. If there is such a concept, then a _stranger_ (meaning here a person who doesn't understand our value system) could share it.
4. If the stranger could share such a descriptive concept, then they could predict how we would apply the thick concept in new cases.
5. Strangers cannot predict how we apply thick concepts in new cases.
6. So no reductive analysis of thick concepts is possible (from 2-5).
7. So non-cognitivism is false (from 1 and 6).

I've separated out line 1 because @Elstein2009 are interested in replying to the argument to line 6, independent of whether non-cognitivism is true. But I think it's common ground that 1 is true, so that extra step is fine.

Now this argument seems bad to me because (as Blackburn pointed out straight away), there is no real reason to think that 2 is correct. Let's take a simple example. This analysis isn't going to work, but it's enough to show that this argument fails. Assume that for a person to be selfish, the following conditions must all be met.

- The person prioritises their interests over those of others.
- The person is all-things-considered a bad person.
- At least part of the explanation of the second point is the first point.

There is nothing in that which a non-cognitivist need reject. But it doesn't follow that there is anything descriptively equivalent to 'selfish'. After all, not everyone who prioritises their interests over those of others is selfish; they have to also satisfy the second clause. Now I don't mean to say that this is a good analysis. It clearly isn't, and we'll get back to that point. But the possibility of it suffices to show that this argument doesn't work.

Elstein and Hurka (on page 519) say that Williams gives a version of the same argument. But they then attribute an argument to Williams which they say is the same argument. That can't possibly be right, since Williams's argument makes no reference to strangers. But I think 2 is part of that alternative argument as well. And maybe they think we can replace 3-5 in McDowell's argument with:

- There is no descriptive concept that is necessarily extensionally equivalent to the thick concept.

I don't know though; that seems like a bold claim. And McDowell certainly isn't taking it as a premise, though maybe Williams is. Anyway, it seems like a bad argument, because it ignores the possibility of analyses like my toy analysis of selfish. Elstein and Hurka say that it is bad because it assumes that any analysis will be 'Descriptively Definite', but I don't think that's the problem. I'm not 100% sure what they mean by that, but I think this analysis of 'selfish' is Descriptively Definite, and it shows that premise 2 is wrong.

But that's not, to my mind, the most interesteding argument in McDowell's paper. I thought the argument in section 5 of McDowell's paper was really fascinating, but I'm not sure it has always been fully appreciated in the subsequent literature. (Not that I've read 100% of it, or even close.) Here's how I'd write it.

1. From the inside, the evaluative part of 'honest' feels non-arbitrary; it doesn't seem like we just like honest things the way we might like a flavour of ice-cream. Call this the non-arbitrariness constraint.
2. The non-arbitrariness constraint requires that we can identify the descriptive features in virtue of which we positively evaluate them, and do so independently of our own evaluation.
3. We can only identify the descriptive parts of our own thick concepts independently of our own evaluations if a stranger could identify them.
4. A stranger could not make this identification - this is both intuitive, and arguably the result of the long Wittgensteinian discussion in section 3.

And now we have a problem. Line 1 says that our own attitudes involving thick concepts satisfy the non-arbitrariness constraint, but lines 2-4 together imply that they could not.

This is why I think it matters that we can't identify the honest, or kind, or cruel, behaviors independently of our values. Given non-cognitivism, the only way we can pick out the kind behaviours are as those that morally resemble, by our lights, the paradigms of kind behaviour. But it would feel hopelessly circular to say that we admire kind behaviour because things only fall under the concept 'kind' if we admire them. So there is a problem for non-cognitvists here.

As a small exegetical point, note the (kind of jerk-ish) footnote about Ayer, where he says that this argument won't trouble all non-cognitivists. I think he means there that Ayer would be happy to say that moral evaluations are completely arbitrary - they are just what we happen to cheer or boo. Whether that's a fair thing to say about Ayer or not, it does mean that we should be taking McDowell to be giving an argument that works against every form of non-cognitivism. But most people who take themselves to be engaging with McDowell don't present arguments that make any distinction amongst non-cognitivists.

If I were a non-cognitivist, I'd try to get out of the problem this way. All that non-arbitrariness requires is that on any given occasion of use, we can specify in a non-circular way why we admire the people we admire. And that's possible even if we can't specify exactly what kindness or honesty is. So think back to the selfish person. For any given selfish person, I can say why I don't admire them: they put their interests ahead of others.

But here we get to a delicate point. By this account of selfishness, I don't have a full account of why I don't admire these people. They may do something else that makes them all-things-considered good. Is that enough to get back into arbitrariness? I think the thing to do here is to make a distinction that's really crucial within thinking about moral explanations.

- Some moral explanations are **conclusive**. Given what we say in explaining the phenomena, it is necessary that the moral evaluation obtain.
- Some moral explanations are **complete**. Given what we say in explaining the phenomena, we don't need anything else to infer that the moral evaluation obtains.

All conclusive explanations are complete, but the converse does not obtain. Or so I think; this gets at a hard question in the metaphysics of morality. To make it more concrete, think about the following example. A says that X is a bad person, and you ask why. A says "X deliberately killed a child." I want to say this is a complete explanation; you now know enough to know why X is bad. But it isn't conclusive. Maybe X is a bomber pilot who bombed a nuclear missile launch site, preventing the start of a nuclear war, but killing a child that (X knew) was close to where the bomb detonated. Probably that was not a bad thing for X to do. (I don't have a lot of sympathy for either absolutist views that say X should have let the nuclear war start, or the kind of view that says it isn't really killing if X was primarily motivated to do something else.)

Now here's the metaphysical point. Go back to the regular case where there are no extenuating circumstances. Does the explanation of why X is a bad person have to include the absence of extenuating circumstances? My view is that it doesn't have to; or at least we can make sense of a theory of moral explanation where it doesn't. On that notion, some explanations (like "X deliberately killed a child") are complete but not conclusive.

So here's how I'd respond to McDowell's argument more carefully. Non-arbitrariness requires that we can (at least in theory) give a complete explanation of our moral attitudes in descriptive terms. But the ability of strangers to predict our evaluations requires that they have a conclusive explanation of the attitudes we have. And there is no reason that we need to have such an explanation, so no reason to think that the stranger has it.

### Elstein and Hurka's Positive Theories

Elstein and Hurka give two (and a half?) different theories. They say the second is for 'virtues', but then the theory applies in the first instance to acts, so I'm a bit puzzled at exactly how the theories are meant to fit together. It's worth setting these out a bit pedantically. Here is the first one - a bit simplified and a bit tidied up from what they give on 522. For some positive thick term T, the account says that x is T if there is some set of properties such that:

  - x has every member of the set
  - Each of the properties is to do with descriptive kind D (which varies for different T)
  - Any y that has every member of the set is good.

This, like the toy analysis of 'selfish' will violate premise 2 of McDowell's original argument. It's a little trickier, but I think it will also be consistent with the inability of strangers to predict how we will continue to apply the term. The stranger might not know, even with a huge amount of data, that there is another set satisfying the second and third clause. 

How will this engage with the non-arbitrariness concern? Here I think it does worse. If there were such sets - and we could identify their members - then our evaluations of selfish people as bad would not feel arbitrary. But if we cannot identify the sets, and Elstein and Hurka give no evidence we can, I suspect it might still feel arbitrary.

They give a second option for 'virtue-related' concepts T. The idea is that an act x is T just in case for some particular  property-function D (which varies by T, but is in some sense descriptive):

- x is D(good)
- Anything that is D(good) is good.

By a property-function here, I mean a function that takes another property as input, and returns a property. So here's a property function.

- D(P)  = the property of sticking to a P goal despite distractions and temptations.

When P is descriptive, D(P) will be descriptive. For instance D(popular) is a descriptive property, the property of sticking to a popular goal despite distractions and temptations. But note that the account here is moralised twice over. We put moral properties both into D(P), and we have a constraint that D(good) is good.

Now the particular instances of this kind of account they give are not I think very plausible. Integrity, for example, doesn't require stickinig to goals that in the abstract good. It requires sticking to goals that are good relative to the 'distractions'. Working on an open access philosophy textbook is a significant good, but it wouldn't show integrity to avoid fighting Nazis to finish it. (The beer mats example is a poor model here.) 

There is a bigger problem for the account of courage. Here D(P) is the property of accepting harm for the sake of things with greater P than the evil of that harm. A deontologist won't accept that all D(value) acts are good, which they need for the definition to make sense. After all, some D(value) acts are rights violations. I think they are thinking that we can use a notion of 'value' in the definition that is sensitive to the badness of violating rights. But that's a very substantial meta-ethical assumption, and it would be bad if the very definition of 'courage' is hostage to that definition.

I think the stuff towards the end about relation R (on page 530) is an attempt to deal with something like this problem. But I don't really understand how it is meant to help get around the problem that rights-based theories are going to say you need a moral constraint (e.g., that the act doesn't violate rights) on any universal moral generalisation.

#### An Argument for Thin Centralism

In the objections and  replies section there was an interesting argument I wanted to tease out. Let's say that for any end E, either the following are both true, or they are both false.

- It shows integrity to stick to a goal of producing E in the face of distractions and temptations.
- It shows courage to stick to a goal of producing E in the face of risk of physical danger.

If there is this kind of correlation over possible values of E, it needs to be explained. And the thin centralist has an easy explanation. Both of these are true when E is a good end, and both are false when it is not. Does the thick centralist (like Williams) have an explanation that's as good? Should they even concede that the correlation obtains?

#### Grounding

Previously I'd summarised Elstein and Hurka's view as follows: x is T iff for some D from the class relevant to T, x is good in virtue of being D. That's not quite what they say. They don't talk about what explains, or grounds, the goodness. They do say that it is a necessary truth that anything which is D is good. But as we've seen discussed ad nauseum in the last 10 years in metaphysics, necessary connections are not quite the same thing as these kind of grounding explanations.

I think they'd be better off appealing to grounding though, especially if you allow contingent grounding. So here is how I would think it is better to give their first analysis. x is T if there is some set of properties such that:

  - x has every member of the set
  - Each of the properties is to do with descriptive kind D (which varies for different T)
  - That x is good is fully grounded in the fact that x has every member of the set.
  
If grounding explanations need only be complete (in the above sense) and not necessarily conclusive, this will allow that the sets might be small enough to be graspable, while it still being true that the explanations they provide are complete.

### Väyrynen's Objections to Semantic Arguments

I'll end this week setting out the argument (as I understand it) in Väyrynen's book [@Vayrynen2013]. It's not quite as clearly signposted as I would have liked, but I think it's a pretty interesting argument.

There is a way of arguing for something in philosophy where the actual argument is really really quick, and then you spend forever arguing that the argument works. So think about the kind of view in philosophy of mathematics that argues that numbers exist the following way.

1. There is an even prime number.
2. So, there are numbers.

On the face of it, that's a compelling argument. The premise is a familiar mathematical truth, and the conclusion follows by first order logic. So that's that. Well, of course anti-realists about numbers have a story to tell about why it's not so simple, and realists have to engage that anti-realist argument. But even after hundreds of pages of such engagement, there's still a good sense in which the realist argument is just the two line argument given here.

That's how I read Väyrynen's book. There is a very simple argument that Elstein and Hurka are mistaken. And the argument also shows that people like McDowell and Foot, who take thick concepts even more seriously than Elstein and Hurka, are also mistaken. Now it isn't that simple to tell whether the simple argument is actually any good. Just like the anti-realist can explain away the apparent argument for the existence of numbers, the supporter of either a reductionist treatment of thick concepts (like Elstein and Hurka) or a non-reductionist treatment (like McDowell and Foot) can explain away the apparent argument. Or at least they can try, and a huge part of Väyrynen's book is about why those explanations don't work. But the initial argument is reasonably simple. I'll run through three versions of that 'original argument' today, and next week we'll look at (a) some possible replies to it, and (b) the positive theory Väyrynen puts in place.

Väyrynen sets up the example using 'lewd', and I don't have any intuitions at all about how 'lewd' works. It's not really in my everyday speech. So I'll instead use 'selfish'. And I'm interested in two possible users of the word 'selfish'. (At least, I want us to have these two users in mind.)

The first kind of user is an ethical egoist, who thinks the descriptive component of 'selfish' does not pick out morally bad behavior, and in fact picks out morally good behavior.

The second kind of user is a consequentialist, who thinks that some people produce all-things-considered better outcomes when they act selfishly than when they try to act altruistically, and so it is good for those people to be a bit selfish.

(Actually what I personally am interested in is what's going on when analysts say that a sporting figure should be a bit more selfish, or isn't selfish enough. I think they mean a version of the second thing. It's almost a platitude in soccer that the great strikers are all a bit selfish, that you have to be a bit selfish to be a great striker. So in that context selfishness is not an unqualified bad.)

Now imagine a person, call him Suárez, does something that puts his own interests above those of some other salient person. And imagine that our speaker, Bloggs, is one of these two kinds of users. Here's Väyrynen's argument from negated uses of thick terms.

1. If Elstein and Hurka are right, Bloggs should deny/reject "Suárez is being selfish", and accept "Suárez is not being selfish". (This is because Suárez being selfish entails, according to Elstein and Hurka, that Suárez is doing something bad, and Bloggs does not believe that he is.)
2. In fact, Bloggs will not deny/reject "Suárez is being selfish", and will not accept "Suárez is not being selfish".
3. So Elstein and Hurka are mistaken.

There is a parallel argument, I think, against the kind of view in McDowell and in Foot.

1. If McDowell's view or Foot's view right, Bloggs should reject "Suárez is being selfish", because to accept it would be to accept that Suárez is criticisable.
2. Bloggs would not reject "Suárez is being selfish".
3. So McDowell's view and Foot's view are both mistaken.

I'm not going to run through the McDowell/Foot version of the criticism in each case. But I do want to stress a structural point. Even though Elstein and Hurka set up their view as a response to McDowell, Väyrynen offers a criticism of them on the basis of what they have in common with McDowell (and hence also with Foot/Williams/etc.)

So that's the argument from negated uses. There is also an argument from conditional uses.

1. If Elstein and Hurka are right, then all users, and hence Bloggs as well, should regard conditionals like "If Suárez is being selfish, he is doing something wrong" as trivial.
2. But Bloggs will not regard that conditional as trivial.
3. So, Elstein and Hurka are wrong.

And there is an argument from questions. Get away from these two particular users, and think about a generic user of 'selfish', who might be from these groups but probably isn't.

1. If Elstein and Hurka are right, then asking "Is Suárez being selfish?" is to ask both about what Suárez did, and about acts like his have certain moral properties.
2. But in fact, a person who asks "Is Suárez being selfish?" is, typically, just asking a descriptive question.
3. So Elstein and Hurka are wrong.

Now in every one of these arguments, the argument for premise 1 is fairly simple. They say 'selfish' has this two-or-three part structure, and premise 1 follows from plugging something with that structure into completely standard theories of assertion, supposition and questioning. The response, in every case, is that the completely standard theory isn't quite right in this particular case. And this isn't an ad hoc response because it turns out there are quite a few cases where the completely standard theory isn't quite right.

So to finish, let's think about a couple of cases where the standard theory fails. First we'll do 'regret', then we'll do 'stopped'. (Väyrynen has examples where 'regret' and 'stopped' appear in the same sentence, but understanding these is really quite hard, and I think they are best put off until we've understood the simple ones.)

To a first approximation, Brian regrets doing X is true just in case Brian did X, and Brian wishes he hadn't. Now think about these three sentences.

1. Brian doesn't regret drinking Red Bull and vodka for breakfast.
2. If Brian regrets drinking Red Bull and vodka for breakfast, then he drank Red Bull and vodka for breakfast.
3. Does Brian regret drinking Red Bull and vodka for breakfast?

To my ear, the 'standard theory' gets 1 and 3 wrong. If (as I hope will be the case when these notes are published) I didn't have Red Bull and vodka for breakfast, then 1 sounds wrong, even though the negation of the truth conditions for "Brian regrets drinking Red Bull and vodka for breakfast" is true. And 3 is asking about my attitudes, not my culinary preferences. But 2 does sound trivial, just like the standard theory predicts.

To a first approximation, Brian has stopped doing X just in case he used to do X, and now he doesn't. Now think about these three sentences.

1. Brian hasn't stopped drinking Red Bull and vodka for breakfast.
2. If Brian has stopped drinking Red Bull and vodka for breakfast, then he used to drink Red Bull and vodka for breakfast.
3. Has Brian stopped drinking Red Bull and vodka for breakfast?

Again, I think the 'standard theory' gets 1 and 3 wrong. I think 1 is not true, even though it looks like the negation of a sentence whose truth conditions are not satisfied. And 3 seems to be asking what I'm having for breakfast now, not what I used to have for breakfast. Though, interestingly, 2 is still somewhat trivial I suspect.

But note the dialectic. Väyrynen has said that given Elstein and Hurka's theory, and some trivial sounding assumptions about how language works (e.g., when a sentence is not true, its negation is true), we get false predictions about particular English sentences. At this stage Elstein and Hurka can argue that the prediction is actually true, or argue that the supplementary assumptions needed to generate it are false. And the best option seems to be to argue that the supplementary assumptions needed to generate it are false. The easiest way to do that is to come up with independent cases where those assumptions fail. That's why we will spend a lot of time discussing regrets, and stops, and all the rest. But that's for next time.





