---
title: "Week Six: Pragmatic Arguments"
description: |
  There are three aims for the week. The first is to go over Väyrynen's negative argument against semantic views. The second is to briefly go over his positive account. And the third is to wrap up this half of the course by looking back at the big questions we were investigating about the fact/value distinction.
author:
  - name: Brian Weatherson
    url: http://brian.weatherson.org
date: 10-11-2021
bibliography: ../../../articles/Rbib.bib
preview: pekka.jpg
categories:
  - fact-value distinction
  - pragmatic model
  - semantic model
  - rejected terms
output:
  distill::distill_article:
    self_contained: false
    toc: true
    toc_depth: 3
    number_sections: true
---

### Väyrynen's Argument Against Semantic Views

I'll start with a few questions I have about what is going on in the argument against the 'semantic view', and then move onto some objections we might have to this argument.

- What is a T-objector? In particular, is it someone who objects to the theory behind T, or is it someone who objects to the term T?

In class I was saying it was the former - someone who objects to the theory. But when I was reading more carefully for this week's prep, there were certainly places where it looked like it was the latter. Still, I think, _think_, that the former reading is correct. The main reason for this is that when the term is introduced, it is credited to @Kyle2013. And in that paper it is unambiguous that the term means someone who objects to the theory behind T.

Why is it so confusing though? Well, because it's part of the positive theory we're going to get that people who disagree with the theory will typically be unhappy using the term. So in fact there will be, according to the positive theory, a massive overlap between the two groups. But even if that's true, I think we're meant to read it so by definition T-objectors object to the theory, and in practice T-objectors object to the term.

- What properties of T-objectors are meant to cause problems for the rival views?

I'd really like to have a clear answer here, but I think I don't. And that's because I think there isn't really meant to be any one snappy feature that is meant to be problematic for the rival view. So let's circle round to it. Let's use a different example from last time, 'generous'. (This is one that Kyle uses.)

A simple problem for a semantic view of 'generous' (on which it entails good in some way) is that someone who denies that it is good to be generous will typically not deny "X is generous". (Assume X does things that we normally describe as generous, but the objector thinks these are not good.) That's easy to explain. There are lots of cases where we think sentence _S_ entails proposition _p_, but someone who denies _p_ won't simply assert _S_ with a negation slotted in somewhere.

Nor is the problem simply that the objectors won't use the word 'generous'. That would also be easy to explain. If you think there is a term that non-conservatively extends the inferential logic of the language, and some of the new inferences are bad ones, you'll not want to use it at all. And that would be a simple model of what the objectors think.

There are a couple of technical terms in that last paragraph that I should explain. In logic, a term is a 'conservative' extension of the language if adding it to the language only lets you prove new things involving the term. So if you have a language without 'and', adding it lets you prove _A, B, therefore A and B_. But it doesn't let you prove any new things not involving 'and'. On the other hand, the standard way to formulate classical logic (and a bunch of non-classical logics) is that adding 'not' is a non-conservative extension. In the language with 'not', you can prove _If A then B, or if B then A_, which you couldn't prove before, even though that doesn't contain 'not'. Now there is a big dispute about whether it's bad to have non-conservative terms in the language. But the standard view (the one that is built into the standard interpretation of classical logic) is that it's fine, as long as those are good inferences.

One way to read Foot is that she thinks thick terms are non-conservative extensions in this sense, but the good thick terms are good non-conservative extensions. So think about how she treats 'rude'. She thinks you can infer from "X was offensive" to "X was rude". And you can infer from "X was rude" to "X was wrong". And maybe your language didn't allow the inference "X was offensive" to "X was wrong" antecedently. At least, it wasn't an analytic inference. If you're opposed in principle to non-conservative extensions (and I'm a little opposed in principle to non-conservative extensions) you'll think this is very very bad. But the orthodox view is that this is fine, provided they are good inferences. And, extending the orthodox view, if a putative term is a non-conservative extension and the new extended inferences are bad, the term literally doesn't have a meaning. (If this isn't too much of a distraction, I can talk about 'tonk' for a while at this point.)

So that's to say, there is a very well worked out theory which would explain why T-objectors would never ever use the term T. But I think the argument is supposed to be that that theory isn't right because they will _sometimes_ use the term. And I think it is in things like rejecting (1) and accepting (2).

(1) If X acted generously, X did something good in some way.
(2) Whether or not X acted generously, what X did was not good in any way.

But one big question - are those the data to be explained? Are there other data that need explaining too?

- What assumptions are we making here about the relationship between meaning and competent use?

I think Väyrynen wants to argue as follows.

1. Rival views say that it is part of the meaning of 'generous' that being generous is good (in a way).
2. But some competent users of 'generous' use it in a way that would be incoherent if it is part of the meaning of 'generous' that being generous is good (in a way).
3. So it is not part of the meaning of 'generous' that being generous is good (in a way).

Now as it stands, that's invalid. We need an extra premise.

- Competent users of a term do not use it in a way that is incoherent.

And that premise is false. For example, some competent users of 'if' say that modus ponens is invalid. (My argument here draws heavily on @Williamson2007. His example of such a user is Vann McGee, and in particular the discussion of modus ponens in his -@McGee1985.) In general, any high level dispute about logic will involve competent users of a term using it incoherently. And we should wonder about Väyrynen's opponent can do by comparing the objectors to deviant logicians. We certainly don't want to argue that logic is incredibly weak because for just about any inference you can find _some_ competent user who rejects the inference. As 

- What exactly is meant to be wrong with the polysemy view?

The polysemy view, as I'm understanding it, is that terms like 'generous' are ambiguous between a meaning on which the have moral entailments, and a meaning on which they don't.  Väyrynen has a very quick discussion of polysemy in section 4.1. And then whenever it comes up in the book he refers back to this. But the arguments there don't seem incredibly strong. They involve assumptions about which meaning the term would have in different contexts that don't seem at all like compulsory assumptions for the polysemy theorist to make.

That said, it is worth spelling out the polysemy theory in some more detail. I'm saying 'polysemy' here not 'ambiguity' because no one thinks that 'generous' is ambiguous in the way that 'bat' or 'bank' are ambiguous. Whatever meaning plurality is there is like in 'book' or 'newspaper'. (Actually 'book' is  very ambiguous, but I mean both of these have sort of type/token meaning pluralities.) So think about these two sentences.

- Brian bought a book.
- Peter bought a book.

If Brian is a bookshop customer, and Peter is an editor at a press, both of these things may be true, but they mean different things. I now own something that weighs a few ounces and is worth a few dollars, Peter owns something with zero weight, but potentially a lot of value. We call this 'polysemy' not 'ambiguity' because while there are multiple meanings here, it's not completely random that the two meanings go together. Indeed, you might think that these are the only real ambiguities. It's not that 'bat' has two meanings, but that there are two English words with the same spelling/pronunciation. Relatedly, you'd be surprised to find a language where the translations of the two occurrences of 'book' had (radically) different spellings/pronunciations.

But could this be what's going on with 'generous'. On reflection, it doesn't seem super plausible. The two meanings don't have that kind of relation. There are better examples however. Think about something that has changed meaning over time. (Here is a list of 20 such words from the Dean of LSA - https://ideas.ted.com/20-words-that-once-meant-something-very-different/.) During the meaning change, it presumably had two meanings. But meaning changes are typically not random, though they do occasionally involve reversing polarity. So these will be cases of polysemy, not ambiguity.

And that's one way to think about about the T-objectors. They think the meaning of the term should change. Sometimes they will push that forward by using the term with the intended new meaning. But more often they will not use the term, because it will be hard for others to know that they intend to use it with a non-standard meaning. I don't really see how that's a worse explanation than what Väyrynen offers, though to be fair I'm not 100% sure what the data is we're supposed to explain.

- Do these terms pass standard tests for polysemy/ambiguity?

The standard way to test whether a term is ambiguous is to get an instance of the term in a sentence where it is meant to do double-duty, and see if a single token can carry both meanings. So if I own a flying mammal, and you own something to hit baseballs with, it's wrong to say

- You and I own bats.

Or at least it's a bit off. To really see the force of the test, imagine a native Catalan speaker who thinks the English word 'cousin' is _ambiguous_ between cosí and cosina. We can show they are wrong by noting that the following is a perfectly good sentence of English.

- I have two cousins: Alice and Paul.

So how do we apply this to 'generous'. It's a bit tricky, since we can't really have two instances in the different extensions. The closest I could get is the following. Francis thinks selfishness is bad, and Ayn thinks it is good. They both utter the words "Brian is selfish". Is this something we can report?

- Francis and Ayn said that Brian is selfish.

It sort of sounds ok to me, which I guess is evidence against the polysemy theory. But I'm not sure that either (a) that it really is bad, or (b) that it is particularly strong evidence, since we had to embed it in a 'said that' operator.

### Väyrynen's Positive View

As I understand it, Väyrynen's view has two components. He agrees with his opponents that a typical utterance of "Brian is generous" suggests that (the speaker believes that) Brian is good in some way. But he wants to say two things about this implication.

- It is a conversational implicature, not something that's part of the meaning of 'generous'.
- It is not-at-issue.

Let's go through these in turn.

Conversational implicatures, in the sense made famous by @Grice1989, are things you can infer from the fact that a speaker said what they did, and are being cooperative, but which are not part of the meaning. So if someone says "Brian fell out of bed and bumped his head", that doesn't strictly speaking mean that I bumped my head while falling out of bed. (At least on standard theories of how the sentence works - this is actually a tricky case.) The sentence would be literally true if I  bumped my head on the staircase coming up to bed, then disoriented by the sore head fell out of bed the next morning. But it would be horribly misleading to use these words to communicate that that's what happened. If the speaker is being cooperative, they would only say this if I bumped my head in the fall. So that's an implicature of the sentence. Once you get the idea, you see implicatures everywhere you look.

Not-at-issue content is a bit trickier. It's content that is at least part of what the speaker means to communicate, but which isn't front and center. So it would be weird to say "That's not true" or "That's not what happened" or anything like that, because the 'that' wouldn't pick out the right thing. So think about this sentence (from the Nightvale pilot).

- Old Woman Josie, out near the car lot, says the Angels revealed themselves to her.

The at-issue content is that Josie made this report about the Angels. If she didn't say that, it would be easy to object to the sentence. But it's not quite so clear that it is part of the at-issue content that Josie is old, or a woman, or out near the car lot. Think about how you'd respond to the sentence if you accepted everything in the sentence except one of those three things.

So now we get to the striking part of Väyrynen's theory - the moral valence of a thick term is both an implicature and not-at-issue. This is a bit funny, since paradigm implicatures are at-issue. But it's not too hard to come up with examples where you get both. In fact, you can get some that look a lot like what Väyrynen wants. Think about using technical terms from a subject that people have *views* about whether you should care about it. So imagine some using some arcane basketball stats to describe Giannis Antetokounmpo's performance in the Finals last summer, or saying what David Chalmers's h-index is. This implicates that you think those statistics are important. But this implicature is not-at-issue; it would feel like changing the subject for a hearer to object to even using the terms. And note that the objector certainly couldn't object by _denying_ what you said.

That's what Väyrynen thinks is going on with thick terms. They are like arcane stats, and the very use of them reflects a way of looking at the world that some might find objectionable. But the people who do find them objectionable won't want to deny the claims made by the users. Nor will they never use the term, as if they were taboo or inconsistent terms. They will use the terms in saying, for instance, why they don't approve of the theory behind them.

Is this a good account? Let's go over that in class. What I want to end the notes with is a bit of a discussion of where this has left us.

### Four Big Questions

1. Is moral realism, either of some fairly spooky kind, or some more reductive kind, true, or is some kind of anti-realism (meaning here non-cognitivism) true?
2. Is there a sharp fact/value distinction?
3. Are thin terms or thick terms more central to moral philosophy as it should be done, or are they equally important?
4. Do thick terms have their evaluative direction as part of their meaning, or are they just descriptive terms that are usually associated with evaluations?

One big way that thick terms entered philosophy was because they were thought to tell on 2, and hence on 1. The best theory of thick terms, Foot argued, implied a negative answer to 2. And a negative answer to 2 implies some kind of realist answer to 1.

But note how one-directional this is. You can have as strong a realism as you like, and pair that with either having a sharp fact/value distinction (as in Moore), or a not at all sharp one (Murdoch). It's just that certain kinds of anti-realism are incompatible with there not being a distinction.

Once thick terms are on the table, a lot of other questions naturally arise. We haven't made it a big focus yet (though it will become more of a focus over the rest of the term), but 3 is a really fascinating question. I touched on it a little last week in the discussion of integrity and honesty, and that led to a really interesting discussion in class I thought.

Finally, it's worth noting that 4, which is the organising question of Väyrynen's book, stands in an odd relation to the rest of the questions. We've seen people who have just about every possible combination of answers to the first 3 questions give an affirmative answer to the last question. And if you have a negative answer to the last question, that doesn't entail anything about the first 2 questions. At most it undermines some arguments for particular answers to the first 2. But presumably it requires you to say that thin terms are more important to moral philosophy, since thick terms are not part of moral philosophy at all!